# device vibration strength
vibration_strength = 1.0

# each hit accumulates some amount of vibration time, set in milliseconds
# warning: setting this too high might keep your device vibrating for a while!
vibration_time = 300

# log levels: ERROR, WARN, INFO, DEBUG, TRACE
log_level = "ERROR"